apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: articom-docs-ingress
  namespace: docs
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: articom.io
      http:
        paths:
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: articom-docs
                port:
                  number: 3000
