
apiVersion: v1
kind: Service
metadata:
  name: articom-docs
  namespace: docs
spec:
  selector:
    app: articom-docs
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

